### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by roth1002** [JmeHsieh/issue_aggregator#3]
The front end / backend pagination need to implement

**Comment by JmeHsieh** [comment]
Cool, thanks!
Just pushed backend implementation: 039c72674ccfbcaa49587fa10559274e92c0797f
👍 👍

**Comment by naush** [comment]
Here is my implementation for the frontend: https://github.com/naush/issue_aggregator/commit/5d7b79933190b83a26eac89384eae4427c57e314.
